# Assignment 1

### To be submitted before 30 May 2020.

An short introduction about PyTorch and about the chosen functions. 
- torch.index_select()
- torch.eq()
- torch.dot()
- torch.fmod()
- torch.inverse()

In [2]:
# Import torch and other required modules
import torch

## Function 1 - torch.index_select()

torch.index_select(input, dim, index, out=None) --> Tensor

index_select is a function that returns a new tensor which has the entries specified in index of the tensor defined in input.

It has the same number of dimension as the original tensor (defined in input). 

In [2]:
# Example 1
#create x using randn with 5 rows and 4 columns
x = torch.randn(5, 4)
x

tensor([[ 0.7081, -0.1952,  0.1616, -0.6794],
        [ 0.2017, -2.0601,  0.4825,  0.0657],
        [ 1.2947,  0.5529, -0.4297, -0.1562],
        [-0.6232,  1.1203, -0.7710,  0.1843],
        [-0.3766,  0.0581, -1.6676, -0.6237]])

In [4]:
#choose the entries you'd like to see in the new tensor
index = torch.tensor([0,2])
index

tensor([0, 2])

In [5]:
#define a dim from -2, -1, 0, 1 where dim -1 = dim 1, dim -2 = dim 0
#dim = 1 => entries 0, 2 column wise

torch.index_select(x, 1, index)

tensor([[ 0.7081,  0.1616],
        [ 0.2017,  0.4825],
        [ 1.2947, -0.4297],
        [-0.6232, -0.7710],
        [-0.3766, -1.6676]])

In [6]:
#if you change the dim to 0, then you'll see that it'll be entry 0, 2 row wise

torch.index_select(x, 0, index)

tensor([[ 0.7081, -0.1952,  0.1616, -0.6794],
        [ 1.2947,  0.5529, -0.4297, -0.1562]])

As the tensor x - created in the beginning - was a rank 2 tensor and had 2 dimensions (dim = 0 and dim = 1), that's what the new tensors created from the function index_select() would have too. 
The above example demostrates how you can create new tensors from entries of another. 

In [7]:
# Example 2 
#create a 3 dimentional tensor
y = torch.randn(3, 3, 4)
y

tensor([[[ 0.5172, -0.5266, -1.5842, -0.8504],
         [-1.7954,  0.6498, -0.5670, -0.1746],
         [-0.5155, -1.1931,  1.7387, -1.6547]],

        [[ 1.0430, -0.1878, -0.8700,  0.9095],
         [ 1.5274, -1.5575,  0.0954, -1.3150],
         [ 0.4056, -1.1424,  1.0748, -0.9034]],

        [[-0.4914, -0.8851,  1.1622,  0.3159],
         [ 1.2296, -1.2334,  0.3211, -1.5192],
         [-1.2191,  1.7833,  0.4993, -1.1859]]])

In [8]:
#define the entries you'd want in your new tensor
indices = torch.tensor([0,1])
indices

tensor([0, 1])

In [9]:
#define a dimention 
#as dim = 0 is associated with rows, and based on the index defined, all tensor remain unchanged
torch.index_select(y, 0, indices)

tensor([[[ 0.5172, -0.5266, -1.5842, -0.8504],
         [-1.7954,  0.6498, -0.5670, -0.1746],
         [-0.5155, -1.1931,  1.7387, -1.6547]],

        [[ 1.0430, -0.1878, -0.8700,  0.9095],
         [ 1.5274, -1.5575,  0.0954, -1.3150],
         [ 0.4056, -1.1424,  1.0748, -0.9034]]])

In [10]:
#try with dim = 2

torch.index_select(y, 2, indices)

tensor([[[ 0.5172, -0.5266],
         [-1.7954,  0.6498],
         [-0.5155, -1.1931]],

        [[ 1.0430, -0.1878],
         [ 1.5274, -1.5575],
         [ 0.4056, -1.1424]],

        [[-0.4914, -0.8851],
         [ 1.2296, -1.2334],
         [-1.2191,  1.7833]]])

In [11]:
torch.index_select(y, 1, index)

tensor([[[ 0.5172, -0.5266, -1.5842, -0.8504],
         [-0.5155, -1.1931,  1.7387, -1.6547]],

        [[ 1.0430, -0.1878, -0.8700,  0.9095],
         [ 0.4056, -1.1424,  1.0748, -0.9034]],

        [[-0.4914, -0.8851,  1.1622,  0.3159],
         [-1.2191,  1.7833,  0.4993, -1.1859]]])

The example above demonstracts the creation of a 3 dimentional tensor from another 3 dimentional tenor

In [3]:
# Example 3 - breaking (to illustrate when it breaks)
z = torch.randn(3, 4)
z

tensor([[ 0.7951, -1.2985, -0.9913, -0.3244],
        [ 0.6757,  0.7724, -0.0403,  0.1759],
        [ 0.6167,  1.2116, -0.3453, -0.7736]])

In [4]:
index = torch.tensor(3)
index

tensor(3)

In [5]:
torch.index_select(z, 0, index)

IndexError: index out of range in self

In the example above, we chose dimension to be 0, which is looking at the tensor row wise. As you can see there is no row with index 3. Its range is [0,2].
Note that, if we took dimenstion to be 1, which is looking at it column wise, then it would've worked. 

In [6]:
inde = torch.tensor(2)
inde

tensor(2)

In [7]:
torch.index_select(z, 2, inde)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

The example above demostrates the invalid input of dimension. Since it only has 2 (0 and 1), so it doesn't span 2. 

This function really triggered an interest in me because of the way it dealt with dimensions. I took my time to see how the entries were extracted when dimension varied. The resource that really helped me understanding dimensions and helped me visualise this is an article written by Aerin Kim- that can be found here: https://medium.com/@aerinykim/numpy-sum-axis-intuition-6eb94926a5d1

## Function 2 - torch.eq()

torch.eq(input, other, out=None) --> Tensor

This function examines two tensors element by element and check if they are equal. 

It returns a tensor but the elements are either 'True' or 'False'

In [2]:
# Example 1 

x = torch.tensor([[1,2], [3,4], [5,6]])

y = torch.tensor([[2,1], [3,4], [5,6]])

torch.eq(x, y)

tensor([[False, False],
        [ True,  True],
        [ True,  True]])

The example above demonstrates the comparsion of the two tensors taking place. So what the function is doing is comparing the tensore element wise. As 1 does not equal 2, the output is False. 

In [3]:
# Example 2 
x = torch.tensor([[1,2], [3,4], [5,6]])

z = torch.tensor([[2,1], [5,6], [3,4]])

torch.eq(x, z)

tensor([[False, False],
        [False, False],
        [False, False]])

The above example indicates that the position matters. All I did for z was change the position of the second and third component of y and the output is very different to example 1. 

In [7]:
# Example 3 
x = torch.tensor([[1,2], [3,4], [5,6]])

torch.eq(torch.tensor(x.dim()), 2)

tensor(True)

Example 3 shows that the function isn't just useful to compare tensors. You can also check the number of dimensions are the same. 

In [8]:
# Example 4 - breaking (to illustrate when it breaks)

x = torch.tensor([[1,2], [3,4], [5,6]])

torch.eq(x, 'a')

TypeError: eq() received an invalid combination of arguments - got (Tensor, str), but expected one of:
 * (Tensor input, Tensor other, *, Tensor out)
 * (Tensor input, Number other, *, Tensor out)


The above example shows that you would only be able to compare tensors to a numerical value and not a string. 

The function torch.eq() interested me because if we had a large dataset, this will help us reduce it by checking if there are any of the same included. 

## Function 3 - torch.dot()

torch.dot(input, tensor) --> Tensor

This function computes the dot product of the two tensors. 

It only accepts one dimensional tensors (rank 1) as they take the form of vectors. 

This returns a tensor of rank 0

In [9]:
# Example 1
x = torch.tensor([3,4])

y = torch.tensor([1,2])

torch.dot(x,y)

tensor(11)

What the above is doing is ((3x1) + (4x2)) = 11. 

In [10]:
# Example 2
m = torch.tensor([3,4, 5, 6, 7, 8])

n = torch.tensor([1,2, 7, 5, 4, 3])

torch.dot(m, n)

tensor(128)

Example two is just a bigger tensor (vector). (3x1)+(4x2)+(5x7)+(6x5)+(7x4)+(8x3) = 128

In [11]:
# Example 3 - breaking

c = torch.randn(2,2,2)

v = torch.randn(2,2,2)

print(torch.dot(c,v))

RuntimeError: 1D tensors expected, got 3D, 3D tensors at /opt/conda/conda-bld/pytorch_1587428266983/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:431

In [12]:
q = torch.randn(2,2)

p = torch.randn(2,2)

print(torch.dot(q,p))

RuntimeError: 1D tensors expected, got 2D, 2D tensors at /opt/conda/conda-bld/pytorch_1587428266983/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:431

To help visualise why these aren't working, dot product only feasible with vectors (which are 1D tensors). Not possible with matrices and 3D tensors. 

torch.dot function was an interesting one to look at because it can get long to compute it manually. This functions gives people opportunity to spend less time on it.  

Dot products are useful for finding angles between 2 vectors or straight lines or angles between intersecting planes. It has many use cases.

## Function 4 - torch.fmod()

fmod(input, divisor, out=None) --> Tensor

This function computes the remainder of division element wise.

The tensor given as input must compose of either integers or floating points.

The divisor can be a tensor but it must match the size of the tensor given as input. 

In [2]:
# Example 1 
x = torch.randn(2,5)

x

tensor([[-0.2517, -0.3057,  2.7854,  0.1773,  0.7291],
        [ 1.3509,  0.0454, -0.0231, -0.4075,  0.3394]])

In [3]:
torch.fmod(x, 0.5)

tensor([[-0.2517, -0.3057,  0.2854,  0.1773,  0.2291],
        [ 0.3509,  0.0454, -0.0231, -0.4075,  0.3394]])

The above example shows the generation of a new tensor based on the remainder of x when divided by 0.5. 

In [5]:
# Example 2 

y = torch.randn(2,5)

y

tensor([[ 1.5806,  0.9117, -1.5203,  2.0758,  0.8727],
        [ 1.5655,  0.8079,  0.3066,  2.1633, -0.0402]])

In [6]:
div = torch.randn(2,5)

div

tensor([[ 0.1591,  1.7832, -0.9690, -0.6447, -1.3046],
        [ 0.5104, -0.7494,  0.3865,  0.8877,  1.4321]])

In [7]:
torch.fmod(y, div)

tensor([[ 0.1484,  0.9117, -0.5512,  0.1419,  0.8727],
        [ 0.0342,  0.0585,  0.3066,  0.3878, -0.0402]])

Example 2 demonstrates how you can divide tensors by tensors of the same size. 

In [9]:
# Example 3 - breaking (to illustrate when it breaks)

z = torch.randn(2,5)

z

tensor([[ 2.0507, -0.1698, -0.7410, -0.9489, -0.4494],
        [ 0.2283,  0.8712,  0.7189,  0.4397,  0.9827]])

In [10]:
divn = torch.randn(1,3)

divn

tensor([[-0.6306,  0.1019,  0.7398]])

In [11]:
torch.fmod(z, divn)

RuntimeError: The size of tensor a (5) must match the size of tensor b (3) at non-singleton dimension 1

Example 3 shows that the two tensors must match the size otherwise, it'll throw an error as above

The function torch.fmod intriguing because maths made simple always makes me a fan!

## Function 5 - torch.inverse()

inverse(input, out=None) --> Tensor

This function takes the inverse of a given square matrix. These matraices can be batches of 2D square tensors to which a tensor compose of individual inverses is returned. 

In [12]:
# Example 1

x = torch.randn(4,4)

x

tensor([[ 0.5421, -0.5602,  3.3080, -0.6643],
        [-0.1791,  0.5164,  0.9068, -0.9018],
        [-1.0950,  0.0482, -0.7268,  0.8043],
        [ 0.6360, -1.0838,  0.3234,  0.2340]])

In [16]:
y = torch.inverse(x)

y

tensor([[ 0.1912, -1.2689, -1.0466, -0.7500],
        [ 0.3957, -1.3085, -0.6229, -1.7784],
        [ 0.4710, -0.4213,  0.0453, -0.4422],
        [ 0.6622, -2.0298, -0.1033, -1.3141]])

This example shows that we inversed a 4 by 4 matrix. y is the inverse of x. 

In [29]:
# Example 2

x = torch.randn(2, 3, 3)

x

tensor([[[-1.7502,  0.3364, -0.1802],
         [-1.2338, -2.7713,  0.3425],
         [-0.4743, -1.5426, -1.4060]],

        [[ 0.3445,  0.4397,  0.0258],
         [-0.1513,  1.1194,  1.7242],
         [ 0.9152,  0.1835,  0.5815]]])

In [30]:
y = torch.inverse(x)

y

tensor([[[-0.5213, -0.0885,  0.0453],
         [ 0.2235, -0.2798, -0.0968],
         [-0.0694,  0.3369, -0.6203]],

        [[ 0.4077, -0.3058,  0.8886],
         [ 2.0302,  0.2153, -0.7286],
         [-1.2822,  0.4133,  0.5510]]])

The example above is of a 3D tensor where you have 2 3 by 3 tensors. How this works is, the inverse of each 3 by 3 tensor is worked out separately and combined in a new tensor, which is the output.  

In [5]:
# Example 3 - breaking (to illustrate when it breaks)

x = torch.randn(4,3)

y = torch.inverse(x)

y

RuntimeError: A must be batches of square matrices, but they are 3 by 4 matrices

The example above breaks because it's not a square matrix.

The function torch.inverse looks at the inverse of rank 2 tensors.

## Conclusion

To conclude the functions we looked at here are:
torch.index_select - creating a tensor based on the index and dim defined 
torch.eq - creating a tensor with True or False outputs, based on element equality 
torch.dot - computing a scalar tensor using the dot product of vectors
torch.fmod - computing a new tensor based on the remainder you get when you divide the defined tensor by the a defined divisor
torch.inverse - computing the inverse of a square matrix

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* Article on dimensions: https://medium.com/@aerinykim/numpy-sum-axis-intuition-6eb94926a5d1

In [17]:
!pip install jovian --upgrade --quiet

In [18]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
